### ISSUE TITLE
add more regexps and question

### ISSUE THREAD

**Issue by hanscees** [origamiofficial/youtube-updater-for-pi-hole#3]
Hi,

I am implementing your code, but it did not work here. 
So after some regexps fun I found that if I add a line of regexps like

```
zgrep -E "reply.r[0-9-]-*sn-[0-9a-z]{8}.gvt*|reply.r[0-9-]-*sn-[0-9a-z]{12}-[0-9a-z]{4}.gvt*|reply.*-.*\.gvt.*\..*\..*\..*" $piLogs \
    | awk -v fIP=$forceIP '{ print fIP, $6 }' >> $workFile
```
I get output like 

```
 rr5.sn-5hnekn7k.gvt1.com
 rr2.sn-5hnekn7z.gvt1.com
 rr4.sn-5hnekn7k.gvt1.com
 rr3.sn-5hnekn76.gvt1.com
 rr3.sn-5hne6nsk.gvt1.com
 rr2.sn-5hne6nsz.gvt1.com
 rr3.sn-5hneknes.gvt1.com
 rr5.sn-5hne6nsz.gvt1.com
 rr2.sn-5hne6nzk.gvt1.com
 rr2.sn-5hnednss.gvt1.com
 rr5.sn-5hne6nzk.gvt1.com
 rr5.sn-5hne6n6e.gvt1.com
 rr3.sn-5hnekn7l.gvt1.com
```

So you might want to see if you have these servers as well perhaps. 

Second a question: you echo these names in a dnsmasq file. But then you mneed to restart the whole server/
Can't you solve that better by doing something like 

for i in file do
pihole -b -nr --comment clever_autoblock $i

no reloading needed

**Comment by hanscees** [comment]
also what I dont understand. 

Your script gets output like:
```

74.125.8.135 rr2.sn-5hne6nsz.gvt1.com
74.125.8.135 rr2.sn-5hne6nzk.gvt1.com
74.125.8.135 rr2.sn-5hnednss.gvt1.com
74.125.8.135 rr2.sn-5hnekn7z.gvt1.com
74.125.8.135 rr3.sn-5hne6nsk.gvt1.com
74.125.8.135 rr3.sn-5hnekn76.gvt1.com
74.125.8.135 rr3.sn-5hnekn7l.gvt1.com
74.125.8.135 rr3.sn-5hneknes.gvt1.com
74.125.8.135 rr4.sn-5hnekn7k.gvt1.com
74.125.8.135 rr5.sn-5hne6n6e.gvt1.com
74.125.8.135 rr5.sn-5hne6nsz.gvt1.com
74.125.8.135 rr5.sn-5hne6nzk.gvt1.com
74.125.8.135 rr5.sn-5hnekn7k.gvt1.com
root@pihole [ ~ ]# 
```

You then move this to a dnsmasq file, but without altering the IP adress.
That seems to me leads to the case where pihole will simply answer the dns requests and resolve to the right ip-adress that google wants.
How does that block anything? 

I am sure I misunderstand something?

**Comment by origamiofficial** [comment]
This script works by modifying the `/etc/hosts` file on the system where Pi-hole is running to block requests to YouTube ads.

When the script is run, it first sets a `forceIP` variable to a specific IP address, which is the IP address of a Google Video server located in the user's geographical region. This is done to prevent the video from buffering due to the ads being blocked.

The script then reads the Pi-hole logs from `/var/log/pihole.log` and searches for entries that match the regular expressions `reply.r[0-9-]-*sn-[0-9a-z]{8}.googlevideo*`, `reply.r[0-9-]-*sn-[0-9a-z]{12}-[0-9a-z]{4}.googlevideo*`, and `reply.*-.*\.googlevideo.*\..*\..*\..*`. These entries correspond to requests for YouTube videos and ads. The script extracts the domain name from each entry and adds an entry to the `hosts.youtube` file with the `forceIP` address and the domain name.

The `hosts.youtube` file is then sorted and duplicates are removed. If the new file is different from the old file, the new file is moved into place and `pihole restartdns` is called to reload the configuration.

The script can be cron'd to run every minute to keep the blocklist up to date.

Overall, this script is a quick and dirty way to block YouTube ads using Pi-hole by intercepting DNS requests and redirecting them to a black hole IP address. It may not be as effective as other ad-blocking methods, and it may break some YouTube videos, but it can help to reduce the number of ads shown.

Please note that `this project is no longer maintained`. Because Pi-hole is only a DNS filter. That is, when a client asks for the 'address' of a name (a web domain, etc), it gives an answer but also filters those answers against the configured block lists. Pi-hole can do nothing with the content AT that address. A web browser can. It can inspect the payload of web requests and alter them on the fly because it made the request for the content not just where it was located. YouTube hosts its ads on the same domains as its content.

**Comment by hanscees** [comment]
Thanks for answering. 
I have adjusted the script for use outside the docker container. 
That wya you dont have to install inside a container and redo that after upgrade
Perhaps useful for somebody

```
#!/bin/bash

# crappy hack that seems to keep YouTube ads to a minumum.
# over two hours of Peppa Pig and no ads. Taking one for the team...
# grub@grub.net v0.11

# Change forceIP to the real IP from an nslookup of a
# googlevideo hostname so you get something in your
# geographical region. You can find one in your
# Pi-hole's query logs.
# They will look something like this:
#     r6---sn-ni5f-tfbl.googlevideo.com

# as root: run this once then run "pihole restartdns"
# You can cron this for auto-updating of the host file.
# Mine fires every minute:
# * * * * * /home/grub/bin/youtube.update.sh 2>&1

## adjusted so it works outside the docker container.
## thats easier since you dont have to add it after every
## docker update

forceIP="74.125.8.135"
namedockerservice="pihole3"

# adjust accoring to your docker volumes
piLogs="/var/lib/docker/volumes/pihole_pihole_log/_data/pihole/pihole.log"
ytHosts="/var/lib/docker/volumes/pihole_pihole_log/_data/pihole/blockhosts.youtube"
dnsmasqFile="/var/lib/docker/volumes/pihole_dnsmasq_data/_data/99-youtube.grublets.conf"


# nothing below here should need changing
ytHosts_docker="/var/log/pihole/blockhosts.youtube"
touch $ytHosts
temp="/root/tmpfile"
touch $temp
echo $temp
workFile="/root/tmpfile"
memoryFile="/root/memfile"
touch $memoryFile

if [ ! -f $dnsmasqFile ]; then  # if extra masqfile does not exist, make it
    echo "addn-hosts=$ytHosts_docker" > $dnsmasqFile
fi

# empty workfile and add previous dns records to it
> $workFile
cp $ytHosts $workFile

#echo `ls -all /root`
# now we get all r...googelvideo lines form logs and redirect them to FIP above
# this makes them non-functional, but ytub accepts it
zgrep -E "reply.r[0-9-]-*sn-[0-9a-z]{8}.googlevideo*|reply.r[0-9-]-*sn-[0-9a-z]{12}-[0-9a-z]{4}.googlevideo*|reply.*-.*\.googlevideo.*\..*\..*\..*" $piLogs \
    | awk -v fIP=$forceIP '{ print fIP, $6 }' >> $workFile

#zgrep -E "reply.r[0-9-]-*sn-[0-9a-z]{8}.gvt*|reply.r[0-9-]-*sn-[0-9a-z]{12}-[0-9a-z]{4}.gvt*|reply.*-.*\.gvt.*\..*\..*\..*" $piLogs \
#    | awk -v fIP=$forceIP '{ print fIP, $6 }' >> $workFile

# now we sort the records and also filter out doubles
sort -u $workFile -o $workFile

# we should filter out whats already in memoryfile
cat $workFile >> $memoryFile
sort -u $memoryFile -o $memoryFile
# this cide works, but ytub just add new records if we just block
#for i in `cat $workFile | egrep video`; do
#lets not blacklist but disgize
#docker exec -it pihole3 pihole -b -nr --comment clever_autoblock $i
#echo $i
#done

#if ! cmp $workFile $ytHosts; then  # my linux knows no cmp alas
if [ "$(wc -l < $workFile)" -eq "$(wc -l < $ytHosts)" ]; then
    echo " nothing todo, bey"
else
# dont move, keep chmod the same. Flush and re-populate file
   >  $ytHosts
   cat $workFile > $ytHosts
   #    mv $workFile $ytHosts mv brakes dns inside docker container
   #chmod 644 $ytHosts
   #  namedockerservice="pihole3"
   docker exec -it pihole3 pihole restartdns reload
#    /usr/local/bin/pihole restartdns reload
fi


```
